# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=64)),
                ('wx_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
